"""db_init

Revision ID: a7b9c425f60f
Revises:
Create Date: 2025-01-28 10:50:30.204639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7b9c425f60f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Criar enum para status
    filestatus_enum = postgresql.ENUM('RECEBIDO', 'CONVERTIDO', 'ASSINADO', 'ENVIADO', name='filestatus', create_type=False)
    filestatus_enum.create(op.get_bind(), checkfirst=True)

    # Tabela de planilhas
    op.create_table('tb_planilhas',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('om', sa.String(length=50), nullable=False),
        sa.Column('evento', sa.String(length=255), nullable=False),
        sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
        sa.Column('tipo', sa.String(length=255), nullable=False),
        sa.Column('status', sa.Enum('RECEBIDO', 'CONVERTIDO', 'ASSINADO', 'ENVIADO', name='filestatus'), nullable=False),
        sa.Column('caminho', sa.String(length=255), nullable=False),
        sa.Column('data_recebimento', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id')
    )

    # Tabela de planilhas convertidas
    op.create_table('tb_planilhas_convertidas',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('planilha_id', sa.UUID(), nullable=False),
        sa.Column('caminho', sa.String(length=255), nullable=False),
        sa.Column('total_xmls_gerados', sa.Integer(), nullable=False),
        sa.Column('data_conversao', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['planilha_id'], ['tb_planilhas.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planilha_id_convertida', 'tb_planilhas_convertidas', ['planilha_id'], unique=False)

    # Tabela de XMLs assinados
    op.create_table('tb_xmls_assinados',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('planilha_convertida_id', sa.UUID(), nullable=False),
        sa.Column('caminho', sa.String(length=255), nullable=False),
        sa.Column('data_assinatura', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['planilha_convertida_id'], ['tb_planilhas_convertidas.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_convertido_id_assinado', 'tb_xmls_assinados', ['planilha_convertida_id'], unique=False)

    # Tabela de XMLs enviados
    op.create_table('tb_xmls_enviados',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('id_xml_assinado', sa.UUID(), nullable=False),
        sa.Column('caminho', sa.String(length=255), nullable=False),
        sa.Column('status_envio', sa.String(length=255), nullable=False),
        sa.Column('protocolo_envio', sa.String(length=255), nullable=False),
        sa.Column('data_envio', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['id_xml_assinado'], ['tb_xmls_assinados.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assinado_id_enviado', 'tb_xmls_enviados', ['id_xml_assinado'], unique=False)

    # Tabela de respostas de envio
    op.create_table('tb_resposta_envio',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('enviado_id', sa.UUID(), nullable=False),
        sa.Column('caminho', sa.String(length=255), nullable=False),
        sa.Column('data_resposta', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['enviado_id'], ['tb_xmls_enviados.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enviado_id_resposta', 'tb_resposta_envio', ['enviado_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enviado_id_resposta', table_name='tb_resposta_envio')
    op.drop_table('tb_resposta_envio')
    op.drop_index('ix_assinado_id_enviado', table_name='tb_xmls_enviados')
    op.drop_table('tb_xmls_enviados')
    op.drop_index('ix_convertido_id_assinado', table_name='tb_xmls_assinados')
    op.drop_table('tb_xmls_assinados')
    op.drop_index('ix_planilha_id_convertida', table_name='tb_planilhas_convertidas')
    op.drop_table('tb_planilhas_convertidas')
    op.drop_table('tb_planilhas')

    # Dropar enum
    sa.Enum(name='filestatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
